spring.application.name=helpdesk
spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk_db
spring.datasource.username=ryan
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update